ALTER TABLE retrieval_results
  ALTER COLUMN start_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN first_byte_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN end_at TYPE TIMESTAMP WITHOUT TIME ZONE;